### ISSUE TITLE
Chapter 1: css files are missing

### ISSUE THREAD

**Issue by hkarakose** [PacktPublishing/Learning-Ionic-Second-Edition#3]
Following is a screenshot from `nav-bar.component.ts` file:

<img width="513" alt="screen shot 2017-07-11 at 11 02 55" src="https://user-images.githubusercontent.com/406291/28057396-90c503fc-6628-11e7-872d-d9d42fd4a905.png">

It imports `nav-bar.component.css` file. But this file does not exist:

<img width="367" alt="screen shot 2017-07-11 at 11 04 26" src="https://user-images.githubusercontent.com/406291/28057428-bbb78fe4-6628-11e7-8336-18759d6392b2.png">

**Comment by sonam-packt** [comment]
Please reopen if the issue still persist
