### ISSUE TITLE
problems with ionic 3

### ISSUE THREAD

**Issue by francese2015** [PacktPublishing/Learning-Ionic-Second-Edition#4]
Hi,
I tried to run the example, but it does not work. May you help me?
this is my environment:
----- this is my environment:
cli packages: (/usr/local/lib/node_modules)

@ionic/cli-utils  : 1.13.1
ionic (Ionic CLI) : 3.13.1
global packages:

cordova (Cordova CLI) : 7.1.0 
local packages:

@ionic/app-scripts : 3.0.0
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.7.1
System:

ios-sim : 5.0.8 
Node    : v6.11.2
npm     : 2.15.12 
OS      : macOS Sierra
Xcode   : Xcode 8.3.3 Build version 8E3004b 
Misc:

backend : pro
-------------
this is the report

Starting app-scripts server: --address 0.0.0.0 --port 8100 
       --livereload-port 35729 --dev-logger-port 53703 - Ctrl+C to cancel
[03:17:25]  watch started ... 
[03:17:25]  build dev started ... 
[03:17:25]  Failed to read the projects ionic.config.json file: Unexpected end of JSON input 
Error: /Users/macrita/IONIC3/ch3ex4/src/app/main.ts was not found. The "main.dev.ts" and "main.prod.ts" files have been deprecated. Please create a new file "main.ts" containing the content of "main.dev.ts", and then delete the deprecated files.
                            For more information, please see the default Ionic project main.ts file here:
                            https://github.com/ionic-team/ionic2-app-base/tree/master/src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (/Users/macrita/IONIC3/ch3ex4/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /Users/macrita/IONIC3/ch3ex4/node_modules/@ionic/app-scripts/dist/build.js:58:21

**Comment by gaurav-packt** [comment]
Please reopen the issue if it still exists.
